# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.14.2

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "client/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: cd client && npm install

      - save_cache:
          paths:
            - client/node_modules
          key: v2-dependencies-{{ checksum "client/package.json" }}

      - run: cd client && npm run build

      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

